---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(corrr)
library(ggpubr)
library(tidymodels)
library(httr)
```

```{r}

solar_import <- read_csv("2801736_system_energy_20220404_to_20230624.csv")
solar_update <- read_csv("2801736_custom_report_230625_230914.csv")
solar_import <- solar_import %>% 
  bind_rows(solar_update)

(solarByDay <- solar_import %>% 
  rename(Date = `Date/Time`) %>% 
  mutate(Date = as.Date(Date, '%m/%d/%Y'), `Energy Produced (kWh)` = `Energy Produced (Wh)`/1000) %>% 
  filter(Date > "2022-04-14")
)

```


```{r}
solarByDay %>% 
  filter(Date > "2022-04-15" & Date < "2023-04-16") %>% 
  summarize(total = sum(`Energy Produced (kWh)`))

```


```{r}
ggplot(solarByDay, aes(Date, `Energy Produced (kWh)`)) +
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  ggtitle("Residential Solar System (15.5 kW)") + 
  geom_smooth(span=.4) 

```


```{r}
weather_import <- read_csv("18078 2022-04-15 to 2023-07-01.csv")

#Get Visual Crossing API credentials from R environment
api_email <- Sys.getenv("visualcrossing_email")
api_key <- Sys.getenv("visualcrossing_key")

#Construct API call
api_base_call <- "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
api_zip <- Sys.getenv("zip_code")
start_date <- "2023-07-02"
end_date <- Sys.Date()
api_params <- "?unitGroup=us&elements=datetime%2CdatetimeEpoch%2Ctempmax%2Ctempmin%2Ctemp%2Chumidity%2Cprecip%2Cprecipprob%2Cprecipcover%2Cpreciptype%2Csnow%2Csnowdepth%2Ccloudcover%2Cvisibility%2Csolarradiation%2Csolarenergy%2Cuvindex%2Csunrise%2Csunset&include=days&key="
api_output <- "&contentType=csv"

api_call_history <- paste(api_base_call,api_zip,'/',start_date,'/',end_date,api_params,api_key,api_output, sep='')

api_response_history = content(GET(api_call_history))

weather_import_latest <- read_csv(api_response_history)

(weather_import <- rbind(weather_import, weather_import_latest))

```

https://www.visualcrossing.com/resources/documentation/weather-data/how-to-obtain-solar-radiation-data/

```{r}

(solar_weather <- weather_import %>% 
   inner_join(solarByDay, by = join_by(datetime == Date)) %>% 
   mutate(daylight = as.numeric(sunset-sunrise,units="mins"), solarenergy_kWh = solarenergy/3.6, type = "Historical")
 )

solar_weather_corr <- solar_weather %>% 
  select(`Energy Produced (kWh)`,tempmax,humidity,precip,precipcover,snow,snowdepth,cloudcover,visibility,solarradiation,,solarenergy,uvindex,daylight) %>% 
  correlate()

write_csv(solar_weather_corr, "solar_weather_corr.csv")

ggplot(solar_weather, aes(solarenergy_kWh,`Energy Produced (kWh)`)) +
  geom_point() +
  geom_smooth(method="lm", formula = y ~ x + 0) +
  #stat_regline_equation(formula = y ~ x + 0) +
  xlab("Solar Energy Measured (kWh per square meter)") 

```

```{r}

solarproduction_model <- linear_reg() %>% 
  fit(`Energy Produced (kWh)` ~ solarenergy_kWh + 0, data=solar_weather)

tidy(solarproduction_model)
```

```{r}
#import_forecast <- read_csv("18078_visualcrossing_forecast_15day_230702.csv")

api_params_forecast <- "?unitGroup=us&elements=datetime%2CdatetimeEpoch%2Ctempmax%2Ctempmin%2Ctemp%2Chumidity%2Cprecip%2Cprecipprob%2Cprecipcover%2Cpreciptype%2Csnow%2Csnowdepth%2Ccloudcover%2Cvisibility%2Csolarradiation%2Csolarenergy%2Cuvindex%2Csunrise%2Csunset&include=days&key="

api_call_forecast <- paste(api_base_call,api_zip,'/',api_params_forecast,api_key,api_output, sep='')

api_response_forecast = content(GET(api_call_forecast))

(import_forecast <- read_csv(api_response_forecast))

forecast <- import_forecast %>%  
   mutate(daylight = as.numeric(sunset-sunrise,units="mins"), solarenergy_kWh = solarenergy/3.6, type = "Forecast")

solar_forecast <- predict(solarproduction_model, new_data = forecast) 
solar_forecast_ci <- predict(solarproduction_model, new_data = forecast, type="conf_int")

#plot_data <- 
forecast <- forecast %>% 
  bind_cols(solar_forecast) %>% 
  bind_cols(solar_forecast_ci) 

forecast <- forecast %>% 
  mutate(`Energy Produced (kWh)` = .pred, `Energy Produced (Wh)` = `Energy Produced (kWh)`*1000)

forecast
```

```{r}
(solar_weather <-  bind_rows(solar_weather,forecast))

ggplot(data=solar_weather, aes(datetime,`Energy Produced (kWh)`)) +
  geom_point(aes(group=type, color=type)) + 
  #geom_smooth(span=.4) +
  xlab("Date") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  ggtitle("Residential Solar System (15.5 kW)") 


```

Shiny Dashboard 

Blog Post

Enphase API? 

Explore predictive relationship further
- sides of house, number of panels, angle of panels
Forecast quality/inconsistencies between Precip amount and coverage -> solarenergy

Tie demand and supply data
Look at 15-minute intervals and demand response opportunities. 
